spring.application.name=api_gateway
server.port=8080

# ===============================
# SPRING CLOUD GATEWAY ROUTES
# ===============================

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=${USER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**,/users/**


# LIBRARY SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=library-service
spring.cloud.gateway.server.webflux.routes[1].uri=${LIBRARY_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/books/**,/departments/**

# LIBRARY SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=borrow-service
spring.cloud.gateway.server.webflux.routes[2].uri=${BORROW_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/borrows/**

# ===============================
# RATE LIMITER (OPTIONAL)
# ===============================

# spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
# spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
# spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
# spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}

# ===============================
# ACTUATOR
# ===============================

# management.endpoints.web.exposure.include=health,info,metrics,prometheus
# management.endpoint.prometheus.enabled=true

# ===============================
# JWT TOKEN CONFIG
# ===============================

jwt.secret=mySuperSecretKeyForJwtTokenGeneration123456

# ===============================
# REDIS CONFIG
# ===============================

# spring.redis.host=localhost
# spring.redis.port=6379

# ===============================
# METRICS TAG
# ===============================

# management.metrics.tags.application=${spring.application.name}

# ===============================
# DISTRIBUTED TRACING
# ===============================

# management.tracing.enabled=true
# management.tracing.sampling.probability=1.0
# management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# ===============================
# LOGGING (TRACE ID)
# ===============================

# logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]