apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-shared-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:                             
    - secretName: shared-secrets
      type: Opaque
      data:
        - objectName: db-username
          key: DB_USERNAME
        - objectName: db-password
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: "717cf210-cb95-4f10-989a-9c402496a0c2"            
    keyvaultName: "rajeshlibrarykv001"       
    objects: |
      array:
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
    tenantId: "7eea860c-4664-4c07-9a6a-83be615daa73" 
