apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: default
data:
  KAFKA_BOOTSTRAP_SERVERS: "library-kafka-kafka-bootstrap.kafka:9092"
  DB_HOST: "library-postgres-server.postgres.database.azure.com"