apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: rajeshlibraryacr001.azurecr.io/user-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # 🌐 Fetch the base host domain from our updated shared ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: DB_HOST
            
            # 🔄 Dynamic Spring Boot URL construction pointing to the private "user_db"
            - name: DB_URL
              value: "jdbc:postgresql://$(DB_HOST):5432/library-users?sslmode=require"
              
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-shared-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: user-service

